services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osebne_finance
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./osebne-finance-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/osebne_finance"
    depends_on:
      - postgres
